/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jonghyunahn/SchoolWork/EE/EE125/project/fedora-slambot/src/slam_sensors/msg/RobotVelocity.msg
 *
 */


#ifndef SLAM_SENSORS_MESSAGE_ROBOTVELOCITY_H
#define SLAM_SENSORS_MESSAGE_ROBOTVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_sensors
{
template <class ContainerAllocator>
struct RobotVelocity_
{
  typedef RobotVelocity_<ContainerAllocator> Type;

  RobotVelocity_()
    : angular_velocity(0.0)
    , linear_velocity(0.0)  {
    }
  RobotVelocity_(const ContainerAllocator& _alloc)
    : angular_velocity(0.0)
    , linear_velocity(0.0)  {
    }



   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;




  typedef boost::shared_ptr< ::slam_sensors::RobotVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_sensors::RobotVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct RobotVelocity_

typedef ::slam_sensors::RobotVelocity_<std::allocator<void> > RobotVelocity;

typedef boost::shared_ptr< ::slam_sensors::RobotVelocity > RobotVelocityPtr;
typedef boost::shared_ptr< ::slam_sensors::RobotVelocity const> RobotVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_sensors::RobotVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_sensors::RobotVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slam_sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'slam_sensors': ['/home/jonghyunahn/SchoolWork/EE/EE125/project/fedora-slambot/src/slam_sensors/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_sensors::RobotVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_sensors::RobotVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_sensors::RobotVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37340f3f2186e83a4c0b06837d532fcc";
  }

  static const char* value(const ::slam_sensors::RobotVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37340f3f2186e83aULL;
  static const uint64_t static_value2 = 0x4c0b06837d532fccULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_sensors/RobotVelocity";
  }

  static const char* value(const ::slam_sensors::RobotVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angular_velocity\n\
float64 linear_velocity\n\
";
  }

  static const char* value(const ::slam_sensors::RobotVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_velocity);
      stream.next(m.linear_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RobotVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_sensors::RobotVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_sensors::RobotVelocity_<ContainerAllocator>& v)
  {
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_SENSORS_MESSAGE_ROBOTVELOCITY_H
